import type { LoadingElement } from "./types";

const requiredElement = <T extends HTMLElement>(id: string) => {
  const element = document.getElementById(id) as T | null;
  if (!element) throw new Error(`Missing DOM element: #${id}`);
  return element;
};

export type BimDomElements = ReturnType<typeof getDomElements>;

export function getDomElements() {
  return {
    app: requiredElement<HTMLElement>("app"),
    profileKmBtn: requiredElement<HTMLButtonElement>("profileKmBtn"),
    profileBimBtn: requiredElement<HTMLButtonElement>("profileBimBtn"),
    backToProfilesBtn: requiredElement<HTMLButtonElement>("backToProfilesBtn"),
    bimStub: requiredElement<HTMLElement>("bimStub"),
    statusText: requiredElement<HTMLSpanElement>("statusText"),
    loadingOverlay: requiredElement<HTMLDivElement>("loadingOverlay"),
    loadingStatus: requiredElement<HTMLSpanElement>("loadingStatus"),
    fileName: requiredElement<HTMLElement>("fileName"),
    modelCount: requiredElement<HTMLElement>("modelCount"),
    selectionCount: requiredElement<HTMLElement>("selectionCount"),
    propertiesOutput: requiredElement<HTMLDivElement>("propertiesOutput"),
    treeOutput: requiredElement<HTMLDivElement>("treeOutput"),
    searchInput: requiredElement<HTMLInputElement>("searchInput"),
    searchOutput: requiredElement<HTMLDivElement>("searchOutput"),
    searchPanel: requiredElement<HTMLElement>("searchPanel"),
    progress: requiredElement<HTMLDivElement>("progress"),
    progressBar: requiredElement<HTMLDivElement>("progressBar"),
    viewport: requiredElement<HTMLDivElement>("viewport"),
    libraryModal: requiredElement<HTMLElement>("libraryModal"),
    libraryStart: requiredElement<HTMLElement>("libraryStart"),
    libraryListPanel: requiredElement<HTMLElement>("libraryListPanel"),
    fragmentList: requiredElement<HTMLDivElement>("fragmentList"),
    exampleList: requiredElement<HTMLDivElement>("exampleList"),
    closeLibraryBtn: requiredElement<HTMLButtonElement>("closeLibraryBtn"),
    chooseFragmentBtn: requiredElement<HTMLButtonElement>("chooseFragmentBtn"),
    addIfcBtn: requiredElement<HTMLButtonElement>("addIfcBtn"),
    libraryBackBtn: requiredElement<HTMLButtonElement>("libraryBackBtn"),
    saveFragmentBtn: requiredElement<LoadingElement>("saveFragmentBtn"),
    shareModelBtn: requiredElement<HTMLButtonElement>("shareModelBtn"),
    shareModal: requiredElement<HTMLElement>("shareModal"),
    shareLinkInput: requiredElement<HTMLInputElement>("shareLinkInput"),
    shareModelName: requiredElement<HTMLElement>("shareModelName"),
    shareCopyStatus: requiredElement<HTMLElement>("shareCopyStatus"),
    closeShareBtn: requiredElement<HTMLButtonElement>("closeShareBtn"),
    copyShareBtn: requiredElement<HTMLButtonElement>("copyShareBtn"),
    topBackBtn: requiredElement<HTMLButtonElement>("topBackBtn"),
    ifcInput: requiredElement<HTMLInputElement>("ifcInput"),
    fragInput: requiredElement<HTMLInputElement>("fragInput"),
    loadIfcBtn: requiredElement<LoadingElement>("loadIfcBtn"),
    loadFragBtn: requiredElement<LoadingElement>("loadFragBtn"),
    fitBtn: requiredElement<LoadingElement>("fitBtn"),
    clearBtn: requiredElement<LoadingElement>("clearBtn"),
    downloadFragBtn: requiredElement<LoadingElement>("downloadFragBtn"),
    hideSelectedBtn: requiredElement<LoadingElement>("hideSelectedBtn"),
    isolateSelectedBtn: requiredElement<LoadingElement>("isolateSelectedBtn"),
    showAllBtn: requiredElement<LoadingElement>("showAllBtn"),
    searchToggleBtn: requiredElement<HTMLButtonElement>("searchToggleBtn"),
    homeViewBtn: requiredElement<HTMLButtonElement>("homeViewBtn"),
    dataBrowserBtn: requiredElement<HTMLButtonElement>("dataBrowserBtn"),
    checksBtn: requiredElement<HTMLButtonElement>("checksBtn"),
    issuesBtn: requiredElement<HTMLButtonElement>("issuesBtn"),
    clashBtn: requiredElement<HTMLButtonElement>("clashBtn"),
    drawingsBtn: requiredElement<HTMLButtonElement>("drawingsBtn"),
    dataPanel: requiredElement<HTMLElement>("dataPanel"),
    dataSummary: requiredElement<HTMLElement>("dataSummary"),
    closeDataPanelBtn: requiredElement<HTMLButtonElement>("closeDataPanelBtn"),
    dataSearchInput: requiredElement<HTMLInputElement>("dataSearchInput"),
    dataCategoryFilter: requiredElement<HTMLSelectElement>("dataCategoryFilter"),
    dataStoreyFilter: requiredElement<HTMLSelectElement>("dataStoreyFilter"),
    highlightFilteredBtn: requiredElement<LoadingElement>("highlightFilteredBtn"),
    exportCsvBtn: requiredElement<HTMLButtonElement>("exportCsvBtn"),
    exportJsonBtn: requiredElement<HTMLButtonElement>("exportJsonBtn"),
    dataTableOutput: requiredElement<HTMLDivElement>("dataTableOutput"),
    checksPanel: requiredElement<HTMLElement>("checksPanel"),
    checksSummary: requiredElement<HTMLElement>("checksSummary"),
    closeChecksPanelBtn: requiredElement<HTMLButtonElement>("closeChecksPanelBtn"),
    runChecksBtn: requiredElement<LoadingElement>("runChecksBtn"),
    idsFileInput: requiredElement<HTMLInputElement>("idsFileInput"),
    idsTitleInput: requiredElement<HTMLInputElement>("idsTitleInput"),
    idsSpecNameInput: requiredElement<HTMLInputElement>("idsSpecNameInput"),
    idsEntityInput: requiredElement<HTMLInputElement>("idsEntityInput"),
    idsPsetInput: requiredElement<HTMLInputElement>("idsPsetInput"),
    idsPropertyInput: requiredElement<HTMLInputElement>("idsPropertyInput"),
    addIdsRequirementBtn: requiredElement<HTMLButtonElement>("addIdsRequirementBtn"),
    saveIdsBtn: requiredElement<HTMLButtonElement>("saveIdsBtn"),
    exportChecksCsvBtn: requiredElement<HTMLButtonElement>("exportChecksCsvBtn"),
    exportChecksJsonBtn: requiredElement<HTMLButtonElement>("exportChecksJsonBtn"),
    checksOutput: requiredElement<HTMLDivElement>("checksOutput"),
    issuesPanel: requiredElement<HTMLElement>("issuesPanel"),
    issuesSummary: requiredElement<HTMLElement>("issuesSummary"),
    closeIssuesPanelBtn: requiredElement<HTMLButtonElement>("closeIssuesPanelBtn"),
    createIssueBtn: requiredElement<LoadingElement>("createIssueBtn"),
    exportIssuesJsonBtn: requiredElement<HTMLButtonElement>("exportIssuesJsonBtn"),
    exportIssuesBcfBtn: requiredElement<HTMLButtonElement>("exportIssuesBcfBtn"),
    clearIssuesBtn: requiredElement<HTMLButtonElement>("clearIssuesBtn"),
    issuesOutput: requiredElement<HTMLDivElement>("issuesOutput"),
    clashPanel: requiredElement<HTMLElement>("clashPanel"),
    clashSummary: requiredElement<HTMLElement>("clashSummary"),
    closeClashPanelBtn: requiredElement<HTMLButtonElement>("closeClashPanelBtn"),
    clashGroupASelect: requiredElement<HTMLSelectElement>("clashGroupASelect"),
    clashGroupBSelect: requiredElement<HTMLSelectElement>("clashGroupBSelect"),
    clashToleranceInput: requiredElement<HTMLInputElement>("clashToleranceInput"),
    runClashBtn: requiredElement<LoadingElement>("runClashBtn"),
    clearClashBtn: requiredElement<HTMLButtonElement>("clearClashBtn"),
    clashOutput: requiredElement<HTMLDivElement>("clashOutput"),
    drawingsPanel: requiredElement<HTMLElement>("drawingsPanel"),
    drawingsSummary: requiredElement<HTMLElement>("drawingsSummary"),
    closeDrawingsPanelBtn: requiredElement<HTMLButtonElement>("closeDrawingsPanelBtn"),
    drawingSourceSelect: requiredElement<HTMLSelectElement>("drawingSourceSelect"),
    drawingViewSelect: requiredElement<HTMLSelectElement>("drawingViewSelect"),
    drawingFarInput: requiredElement<HTMLInputElement>("drawingFarInput"),
    annotationTypeSelect: requiredElement<HTMLSelectElement>("annotationTypeSelect"),
    annotationTextInput: requiredElement<HTMLInputElement>("annotationTextInput"),
    addAnnotationBtn: requiredElement<LoadingElement>("addAnnotationBtn"),
    clearAnnotationsBtn: requiredElement<HTMLButtonElement>("clearAnnotationsBtn"),
    generateDrawingBtn: requiredElement<LoadingElement>("generateDrawingBtn"),
    clearDrawingsBtn: requiredElement<HTMLButtonElement>("clearDrawingsBtn"),
    drawingsOutput: requiredElement<HTMLDivElement>("drawingsOutput"),
    searchBtn: requiredElement<LoadingElement>("searchBtn"),
    clearSearchBtn: requiredElement<LoadingElement>("clearSearchBtn"),
  };
}
