import type { LoadingElement } from "../types";
import { requiredElement } from "./dom-helpers";

export function getViewerDom() {
  return {
    app: requiredElement<HTMLElement>("app"),
    profileKmBtn: requiredElement<HTMLButtonElement>("profileKmBtn"),
    profileBimBtn: requiredElement<HTMLButtonElement>("profileBimBtn"),
    backToProfilesBtn: requiredElement<HTMLButtonElement>("backToProfilesBtn"),
    bimStub: requiredElement<HTMLElement>("bimStub"),
    statusText: requiredElement<HTMLSpanElement>("statusText"),
    loadingOverlay: requiredElement<HTMLDivElement>("loadingOverlay"),
    loadingStatus: requiredElement<HTMLSpanElement>("loadingStatus"),
    loadingCancelBtn: requiredElement<HTMLButtonElement>("loadingCancelBtn"),
    fileName: requiredElement<HTMLElement>("fileName"),
    modelCount: requiredElement<HTMLElement>("modelCount"),
    selectionCount: requiredElement<HTMLElement>("selectionCount"),
    propertiesOutput: requiredElement<HTMLDivElement>("propertiesOutput"),
    treeOutput: requiredElement<HTMLDivElement>("treeOutput"),
    searchInput: requiredElement<HTMLInputElement>("searchInput"),
    searchOutput: requiredElement<HTMLDivElement>("searchOutput"),
    searchPanel: requiredElement<HTMLElement>("searchPanel"),
    progress: requiredElement<HTMLDivElement>("progress"),
    progressBar: requiredElement<HTMLDivElement>("progressBar"),
    viewport: requiredElement<HTMLDivElement>("viewport"),
    libraryModal: requiredElement<HTMLElement>("libraryModal"),
    libraryStart: requiredElement<HTMLElement>("libraryStart"),
    libraryListPanel: requiredElement<HTMLElement>("libraryListPanel"),
    fragmentList: requiredElement<HTMLDivElement>("fragmentList"),
    exampleList: requiredElement<HTMLDivElement>("exampleList"),
    closeLibraryBtn: requiredElement<HTMLButtonElement>("closeLibraryBtn"),
    chooseFragmentBtn: requiredElement<HTMLButtonElement>("chooseFragmentBtn"),
    addIfcBtn: requiredElement<HTMLButtonElement>("addIfcBtn"),
    libraryBackBtn: requiredElement<HTMLButtonElement>("libraryBackBtn"),
    saveFragmentBtn: requiredElement<LoadingElement>("saveFragmentBtn"),
    shareModelBtn: requiredElement<HTMLButtonElement>("shareModelBtn"),
    shareModal: requiredElement<HTMLElement>("shareModal"),
    shareLinkInput: requiredElement<HTMLInputElement>("shareLinkInput"),
    shareModelName: requiredElement<HTMLElement>("shareModelName"),
    shareCopyStatus: requiredElement<HTMLElement>("shareCopyStatus"),
    closeShareBtn: requiredElement<HTMLButtonElement>("closeShareBtn"),
    copyShareBtn: requiredElement<HTMLButtonElement>("copyShareBtn"),
    topBackBtn: requiredElement<HTMLButtonElement>("topBackBtn"),
    ifcInput: requiredElement<HTMLInputElement>("ifcInput"),
    fragInput: requiredElement<HTMLInputElement>("fragInput"),
    loadIfcBtn: requiredElement<LoadingElement>("loadIfcBtn"),
    emptyBimState: requiredElement<HTMLElement>("emptyBimState"),
    emptyLoadIfcBtn: requiredElement<HTMLButtonElement>("emptyLoadIfcBtn"),
    emptyExampleBtn: requiredElement<HTMLButtonElement>("emptyExampleBtn"),
    emptyLibraryBtn: requiredElement<HTMLButtonElement>("emptyLibraryBtn"),
    loadFragBtn: requiredElement<LoadingElement>("loadFragBtn"),
    fitBtn: requiredElement<LoadingElement>("fitBtn"),
    clearBtn: requiredElement<LoadingElement>("clearBtn"),
    downloadFragBtn: requiredElement<LoadingElement>("downloadFragBtn"),
    hideSelectedBtn: requiredElement<LoadingElement>("hideSelectedBtn"),
    isolateSelectedBtn: requiredElement<LoadingElement>("isolateSelectedBtn"),
    showAllBtn: requiredElement<LoadingElement>("showAllBtn"),
    searchToggleBtn: requiredElement<HTMLButtonElement>("searchToggleBtn"),
    homeViewBtn: requiredElement<HTMLButtonElement>("homeViewBtn"),
    dataBrowserBtn: requiredElement<HTMLButtonElement>("dataBrowserBtn"),
    checksBtn: requiredElement<HTMLButtonElement>("checksBtn"),
    issuesBtn: requiredElement<HTMLButtonElement>("issuesBtn"),
    clashBtn: requiredElement<HTMLButtonElement>("clashBtn"),
    drawingsBtn: requiredElement<HTMLButtonElement>("drawingsBtn"),
    searchBtn: requiredElement<LoadingElement>("searchBtn"),
    clearSearchBtn: requiredElement<LoadingElement>("clearSearchBtn"),
  };
}
